version: "3.7"

services:
  item-app:
    image: mdrahano12/item-app:v1
    ports:
      - 8080:80
    depends_on: 
      - item-db
    restart: on-failure


  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db
    restart: on-failure

volumes:
  app-db: